# Generated by Django 4.2.6 on 2023-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="salon\\static\\images")),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
